spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: 123456
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
