security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: statistics-mongodb
      username: user
      password: 123456
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://exchangeratesapi.io/api